
services:

  postgres : 
    image: postgres:latest
    container_name: kata-postgres
    restart: always 
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - "5432:5432"
  
  mongo : 
    image: mongo:latest
    container_name: kata-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports : 
      - "27017:27017"


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kata-backend
    depends_on: 
      - postgres
      - mongo
    ports:
      - "8000:8000"
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

    restart: unless-stopped
    env_file: 
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]